#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "indexes"
EXCLUDE = {
    "indexes/system-index.json",
    "indexes/semantic-documents.jsonl",
    "indexes/BLOCK_CATALOG.generated.md",
    "indexes/KNOWLEDGE_CATALOG.generated.md",
}


def git_value(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()
    except Exception:
        return "unknown"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def first(text: str, patterns: list[str]) -> str | None:
    for pattern in patterns:
        match = re.search(pattern, text, re.I | re.M)
        if match:
            return match.group(1).strip().strip("` ")
    return None


def kind(rel: str) -> str:
    if rel.endswith("/BLOCK.md"):
        return "domain-block-entrypoint"
    if rel.startswith("knowledge-library/"):
        return "knowledge-entry"
    if rel.startswith("blocks/"):
        return "domain-block-artifact"
    if rel.startswith("docs/"):
        return "system-standard"
    if rel.startswith("skills/"):
        return "skill-artifact"
    if rel.startswith("agent-library/"):
        return "agent-artifact"
    if rel.startswith("projects/"):
        return "project-artifact"
    return "repository-artifact"


def domain(rel: str) -> str:
    parts = rel.split("/")
    if parts[0] in {"blocks", "skills", "projects"} and len(parts) > 1:
        return parts[1]
    if parts[0] == "knowledge-library" and len(parts) > 1:
        return f"knowledge:{parts[1]}"
    return "system"


def markdown_files() -> list[Path]:
    files = []
    for path in ROOT.rglob("*.md"):
        rel = path.relative_to(ROOT).as_posix()
        if rel in EXCLUDE or ".git" in path.parts or "node_modules" in path.parts:
            continue
        files.append(path)
    return sorted(files)


def artifact(path: Path) -> dict:
    rel = path.relative_to(ROOT).as_posix()
    text = read(path)
    headings = re.findall(r"^#{1,6}\s+(.+)$", text, re.M)
    title = headings[0] if headings else path.stem
    status = first(text, [r"^Lifecycle status:\s*(.+)$", r"^Current status:\s*(.+)$", r"^Status:\s*(.+)$"])
    date = first(text, [r"^Updated:\s*(.+)$", r"^Captured:\s*(.+)$", r"^Date checked:\s*(.+)$", r"^Date:\s*(.+)$"])
    return {
        "path": rel,
        "title": title,
        "type": kind(rel),
        "domain": domain(rel),
        "status": status,
        "date": date,
        "sha256": hashlib.sha256(text.encode()).hexdigest(),
        "headings": headings,
    }


def chunks(path: Path, item: dict) -> list[dict]:
    text = read(path)
    parts = re.split(r"(?=^#{1,6}\s+)", text, flags=re.M)
    rows = []
    for index, part in enumerate(parts):
        part = part.strip()
        if not part:
            continue
        heading_match = re.match(r"^#{1,6}\s+(.+)$", part.splitlines()[0])
        heading = heading_match.group(1) if heading_match else item["title"]
        for offset in range(0, len(part), 3000):
            text_chunk = part[offset:offset + 3000].strip()
            chunk_id = hashlib.sha256(f"{item['path']}|{index}|{offset}|{text_chunk}".encode()).hexdigest()[:24]
            rows.append({
                "chunk_id": chunk_id,
                "source_path": item["path"],
                "heading": heading,
                "type": item["type"],
                "domain": item["domain"],
                "status": item["status"] or "unknown",
                "text": text_chunk,
            })
    return rows


def catalog(title: str, rows: list[dict], prefix: str) -> str:
    lines = [f"# {title}", "", "Generated by `scripts/build_system_index.py`. Do not edit manually.", "", "| Path | Type | Domain | Status |", "|---|---|---|---|"]
    for row in rows:
        if row["path"].startswith(prefix):
            lines.append(f"| `{row['path']}` | `{row['type']}` | `{row['domain']}` | `{row['status'] or 'unknown'}` |")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(exist_ok=True)
    files = markdown_files()
    rows = [artifact(path) for path in files]
    payload = {
        "schema_version": 1,
        "repository": "oleg3479881328-code/Project-Execution-OS",
        "repository_commit": git_value("rev-parse", "HEAD"),
        "generated_at": git_value("show", "-s", "--format=%cI", "HEAD"),
        "artifact_count": len(rows),
        "artifacts": rows,
    }
    (OUT / "system-index.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    with (OUT / "semantic-documents.jsonl").open("w", encoding="utf-8") as handle:
        for path, item in zip(files, rows):
            for row in chunks(path, item):
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    (OUT / "BLOCK_CATALOG.generated.md").write_text(catalog("Generated Block Catalog", rows, "blocks/"), encoding="utf-8")
    (OUT / "KNOWLEDGE_CATALOG.generated.md").write_text(catalog("Generated Knowledge Catalog", rows, "knowledge-library/"), encoding="utf-8")
    print(f"Indexed {len(rows)} Markdown files")


if __name__ == "__main__":
    main()
