param(
    [string]$PortalRoot = "",
    [string]$AllowlistPath = ""
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    return Split-Path -Parent $PSScriptRoot
}

function Assert-PathInside {
    param(
        [string]$ChildPath,
        [string]$ParentPath,
        [string]$Label
    )

    $child = [System.IO.Path]::GetFullPath($ChildPath)
    $parent = [System.IO.Path]::GetFullPath($ParentPath)

    if (-not $child.StartsWith($parent, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "$Label path escapes expected root. Path=$child Root=$parent"
    }
}

function Ensure-MarkdownFrontmatter {
    param(
        [string]$Text,
        [string]$Title
    )

    if ($Text -match '^\s*---\s*$') {
        return $Text
    }

    $safeTitle = $Title.Replace('"', '\"')
    return @"
---
title: "$safeTitle"
---

$Text
"@
}

$repoRoot = Get-RepoRoot

if ([string]::IsNullOrWhiteSpace($PortalRoot)) {
    $PortalRoot = Join-Path $repoRoot "Project-Execution-OS-Library-Portal"
}

if ([string]::IsNullOrWhiteSpace($AllowlistPath)) {
    $AllowlistPath = Join-Path $repoRoot "docs\KNOWLEDGE_LIBRARY_PUBLIC_ALLOWLIST.json"
}

$portalRootResolved = [System.IO.Path]::GetFullPath($PortalRoot)
$contentRoot = Join-Path $portalRootResolved "content"

if (-not (Test-Path -LiteralPath $portalRootResolved)) {
    throw "Quartz portal folder not found: $portalRootResolved"
}

if (-not (Test-Path -LiteralPath $AllowlistPath)) {
    throw "Allowlist file not found: $AllowlistPath"
}

Assert-PathInside -ChildPath $contentRoot -ParentPath $portalRootResolved -Label "Quartz content"

$entries = Get-Content -Raw -Path $AllowlistPath | ConvertFrom-Json

if (-not $entries -or $entries.Count -eq 0) {
    throw "Allowlist is empty."
}

if (Test-Path -LiteralPath $contentRoot) {
    Get-ChildItem -LiteralPath $contentRoot -Force | Remove-Item -Recurse -Force
} else {
    New-Item -ItemType Directory -Path $contentRoot | Out-Null
}

$landingLinks = New-Object System.Collections.Generic.List[string]

foreach ($entry in $entries) {
    if (-not $entry.source -or -not $entry.destination) {
        throw "Each allowlist entry must include source and destination."
    }

    $sourcePath = Join-Path $repoRoot $entry.source
    $destinationPath = Join-Path $contentRoot $entry.destination
    $destinationDir = Split-Path -Parent $destinationPath

    Assert-PathInside -ChildPath $sourcePath -ParentPath $repoRoot -Label "Source"
    Assert-PathInside -ChildPath $destinationPath -ParentPath $contentRoot -Label "Destination"

    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Source file missing: $sourcePath"
    }

    New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null

    $extension = [System.IO.Path]::GetExtension($sourcePath)
    if ($extension -ieq ".md") {
        $content = Get-Content -Raw -Path $sourcePath
        $title = if ($entry.title) { [string]$entry.title } else { [System.IO.Path]::GetFileNameWithoutExtension($destinationPath) }
        $content = Ensure-MarkdownFrontmatter -Text $content -Title $title
        Set-Content -Path $destinationPath -Value $content -Encoding UTF8
    } else {
        Copy-Item -LiteralPath $sourcePath -Destination $destinationPath -Force
    }

    $linkTarget = [System.IO.Path]::ChangeExtension($entry.destination, $null).Replace("\", "/").TrimEnd(".")
    if ($linkTarget.EndsWith("/index")) {
        $linkTarget = $linkTarget.Substring(0, $linkTarget.Length - "/index".Length) + "/"
    }
    $linkTitle = if ($entry.title) { [string]$entry.title } else { [System.IO.Path]::GetFileNameWithoutExtension($destinationPath) }
    $landingLinks.Add("- [[${linkTarget}|$linkTitle]]")
}

$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
$landingPage = @"
---
title: "Project Execution OS Library"
---

# Project Execution OS Library

This portal is a curated browser layer over the `Project-Execution-OS` knowledge library.

It is generated from an explicit allowlist, not from whole-repository publication.

## Included Starter Pages

$(($landingLinks -join "`r`n"))

## Source Model

- Canonical authoring stays in the main GitHub-backed repository.
- Obsidian opens that repository locally as a vault.
- Quartz previews only the copied allowlisted subset.

## Safety Note

If a file is not in the allowlist, it should not appear in this portal.

Generated by `scripts/sync-public-library-to-quartz.ps1` on $generatedAt.
"@

Set-Content -Path (Join-Path $contentRoot "index.md") -Value $landingPage -Encoding UTF8

Write-Host "Synced $($entries.Count) allowlisted items to $contentRoot"
