import { writeFile } from 'node:fs/promises';
const ratio = (a, b) => b ? a / b : 0;
export async function writeReports(outDir, data) {
  const r = data.raw; const v = data.rendered;
  const report = { url: data.url, crawled_at: data.crawledAt, runtime: data.runtime, raw: { http_status: r.status, final_url: r.finalUrl, image_count: r.media.length, readability_chars: r.readability.chars, readability_words: r.readability.words }, rendered: { final_url: v.finalUrl, image_count: v.media.length, readability_chars: v.readability.chars, readability_words: v.readability.words, screenshot_path: 'fullpage.png' }, machine: { aria_snapshot_path: 'aria.yml', axe_violation_count: v.axe.violations.length }, parity: { image_gain_ratio: ratio(v.media.length, Math.max(r.media.length, 1)), image_delta: v.media.length - r.media.length, raw_content_coverage_ratio: ratio(v.readability.chars, Math.max(r.readability.chars, 1)), content_char_delta: v.readability.chars - r.readability.chars, alt_coverage_ratio: ratio(v.media.filter(x => x.alt.trim()).length, Math.max(v.media.length, 1)) }, assumptions: ['Raw HTML is used as the conservative view for crawlers that do not execute JavaScript; crawler capabilities vary.'], errors: [...(r.error ? [r.error] : []), ...(v.error ? [v.error] : []), ...v.consoleErrors.map(x => `console: ${x}`), ...v.requestFailures.map(x => `request: ${x.url} (${x.failure})`)], hypothesis_result: v.media.length > r.media.length || v.readability.chars > r.readability.chars * 1.25 ? 'confirmed' : (v.media.length === r.media.length && v.readability.chars === r.readability.chars ? 'not_confirmed' : 'inconclusive') };
  await writeFile(`${outDir}/report.json`, JSON.stringify(report, null, 2));
  const md = `# Website Intelligence MVP — Peterloon\n\n- Hypothesis result: **${report.hypothesis_result}**\n- Raw images: ${r.media.length}; rendered images: ${v.media.length}; delta: ${report.parity.image_delta}; gain ratio: ${report.parity.image_gain_ratio.toFixed(3)}\n- Raw readable text: ${r.readability.chars} chars / ${r.readability.words} words\n- Rendered readable text: ${v.readability.chars} chars / ${v.readability.words} words\n- Raw-to-rendered coverage ratio: ${report.parity.raw_content_coverage_ratio.toFixed(3)}\n- Rendered non-empty ALT coverage: ${(report.parity.alt_coverage_ratio * 100).toFixed(1)}%\n- Axe violations: ${report.machine.axe_violation_count}\n\nThe classification is based on these deterministic measurements; raw HTML is only a configured crawler assumption, not a universal crawler fact.\n`;
  await writeFile(`${outDir}/report.md`, md); return report;
}
